version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-07-14 to 2021-03-15 by week" --skip-existing --output-format=csv.gz --output-dir=output/measures
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv.gz

  generate_practice_variables:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_practice --skip-existing --output-format=dta --output-dir=output
    outputs:
      highly_sensitive:
        cohort: output/input_practice.dta

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --skip-existing --output-dir=output/measures
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        measure_csv: output/measures/measure_*.csv

  run_practice_variables:
    run: stata-mp:latest analysis/practice_variables.do
    needs: [generate_practice_variables]
    outputs:
      moderately_sensitive:
        model: output/practice_variables.dta
        model2: output/practice_variables.xlsx

  run_model:
    run: stata-mp:latest analysis/model.do
    needs: [generate_measures, run_practice_variables]
    outputs:
      moderately_sensitive:
        model1: output/PerProtocol.xlsx
        model2: output/DiD_weekly.xlsx
        data: output/process_eval.dta
        check: output/weekly_check.xlsx
        check2: output/practice_weekly_glmm.xlsx
        model3: output/CITS_weekly.xlsx
        model4: output/CITS_RandInt.xlsx
        plot1: output/rti_plot.pdf
        plot2: output/arti_plot.pdf
        plot3: output/gastro_plot.pdf
        plot4: output/coviddiag_plot.pdf
        plot5: output/covidsympsens_plot.pdf
        plot6: output/covidsympspec_plot.pdf
        plot7: output/antibio_plot.pdf
        plot8: output/adm_plot.pdf

  run_process_evaluation:
    run: stata-mp:latest analysis/process_eval.do
    needs: [run_model]
    outputs:
      moderately_sensitive:
        model1: output/process_eval.xlsx
        model2: output/process_eval_cat.xlsx
        model3: output/process_eval2.xlsx
        model4: output/process_eval_cat2.xlsx
        data: output/process_eval_check.csv